language: node_js
sudo: required
cache: yarn
env:
  global:
  - ENCRYPTION_LABEL: 6c432af47126
  - COMMIT_AUTHOR_EMAIL: patternfly-build@redhat.com
  - COMMIT_AUTHOR_USERNAME: patternfly-build
  - TRIGGER_REPO_SLUG: jschuler/pf-org
  - TRIGGER_REPO_BRANCH: master
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: out/
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
notifications:
  email: false
git:
  depth: 1
before_install:
- nvm install 4
- if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
- npm install -g grunt-cli gatsby-cli
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
- export PATH=$HOME/.yarn/bin:$PATH
- yarn bootstrap
install: true
script:
- yarn prebuild
- yarn build
after_success: |
  cd "$TRAVIS_BUILD_DIR"
  # This generates a `web` directory containing the website.
  mkdir -p out/pf4
  cp -R $TRAVIS_BUILD_DIR/packages/patternfly-3/_site/. $TRAVIS_BUILD_DIR/out/
  cp -R $TRAVIS_BUILD_DIR/packages/patternfly-4/public/. $TRAVIS_BUILD_DIR/out/pf4/